def checkpoint_new_category_in_response():
    from h2o.estimators.deeplearning import H2ODeepLearningEstimator
    sv = h2o.upload_file(pyunit_utils.locate('smalldata/iris/setosa_versicolor.csv'))
    iris = h2o.upload_file(pyunit_utils.locate('smalldata/iris/iris.csv'))
    sv = h2o.upload_file(pyunit_utils.locate('smalldata/iris/setosa_versicolor.csv'))
    iris = h2o.upload_file(pyunit_utils.locate('smalldata/iris/iris.csv'))
    m1 = H2ODeepLearningEstimator(epochs=100)
    m1.train(x=[0, 1, 2, 3], y=4, training_frame=sv)
    try:
        m2 = H2ODeepLearningEstimator(checkpoint=m1.model_id, epochs=200)
        m2.train(x=[0, 1, 2, 3], y=4, training_frame=iris)
        assert False, 'Expected continued model-building to fail with new categories introduced in response'
    except EnvironmentError:
        pass
